// D&D Stat Modifier Calculation
export const calculateModifier = (statValue) => {
  return Math.floor((statValue - 10) / 2);
};

// D&D Stat Descriptions (for reference)
export const statDescriptions = {
  Strength: {
    1: "Morbidly weak, has significant trouble lifting own limbs",
    2: "Needs help to stand, can be knocked over by strong breezes",
    3: "Needs help to stand, can be knocked over by strong breezes",
    4: "Knocked off balance by swinging something dense",
    5: "Knocked off balance by swinging something dense",
    6: "Difficulty pushing an object of their weight",
    7: "Difficulty pushing an object of their weight",
    8: "Has trouble even lifting heavy objects",
    9: "Has trouble even lifting heavy objects",
    10: "Can literally pull their own weight",
    11: "Can literally pull their own weight",
    12: "Carries heavy objects for short distances",
    13: "Carries heavy objects for short distances",
    14: "Visibly toned, throws small objects for long distances",
    15: "Visibly toned, throws small objects for long distances",
    16: "Carries heavy objects with one arm",
    17: "Carries heavy objects with one arm",
    18: "Can break objects like wood with bare hands",
    19: "Can break objects like wood with bare hands",
    20: "Able to out-wrestle a work animal or catch a falling person",
    21: "Able to out-wrestle a work animal or catch a falling person",
    22: "Can pull very heavy objects at appreciable speeds",
    23: "Can pull very heavy objects at appreciable speeds",
    24: "Pinnacle of brawn, able to out-lift several people",
    25: "Pinnacle of brawn, able to out-lift several people"
  },
  Dexterity: {
    1: "Barely mobile, probably significantly paralyzed",
    2: "Incapable of moving without noticeable effort or pain",
    3: "Incapable of moving without noticeable effort or pain",
    4: "Visible paralysis or physical difficulty",
    5: "Visible paralysis or physical difficulty",
    6: "Significant klutz or very slow to react",
    7: "Significant klutz or very slow to react",
    8: "Somewhat slow, occasionally trips over own feet",
    9: "Somewhat slow, occasionally trips over own feet",
    10: "Capable of usually catching a small tossed object",
    11: "Capable of usually catching a small tossed object",
    12: "Able to often hit large targets",
    13: "Able to often hit large targets",
    14: "Can catch or dodge a medium-speed surprise projectile",
    15: "Can catch or dodge a medium-speed surprise projectile",
    16: "Able to often hit small targets",
    17: "Able to often hit small targets",
    18: "Light on feet, able to often hit small moving targets",
    19: "Light on feet, able to often hit small moving targets",
    20: "Graceful, able to flow from one action into another easily",
    21: "Graceful, able to flow from one action into another easily",
    22: "Very graceful, capable of dodging a number of thrown objects",
    23: "Very graceful, capable of dodging a number of thrown objects",
    24: "Moves like water, reacting to all situations with almost no effort",
    25: "Moves like water, reacting to all situations with almost no effort"
  },
  Constitution: {
    1: "Minimal immune system, body reacts violently to anything foreign",
    2: "Frail, suffers frequent broken bones",
    3: "Frail, suffers frequent broken bones",
    4: "Bruises very easily, knocked out by a light punch",
    5: "Bruises very easily, knocked out by a light punch",
    6: "Unusually prone to disease and infection",
    7: "Unusually prone to disease and infection",
    8: "Easily winded, incapable of a full day's hard labor",
    9: "Easily winded, incapable of a full day's hard labor",
    10: "Occasionally contracts mild sicknesses",
    11: "Occasionally contracts mild sicknesses",
    12: "Can take a few hits before being knocked unconscious",
    13: "Can take a few hits before being knocked unconscious",
    14: "Able to labor for twelve hours most days",
    15: "Able to labor for twelve hours most days",
    16: "Easily shrugs off most illnesses",
    17: "Easily shrugs off most illnesses",
    18: "Able to stay awake for days on end",
    19: "Able to stay awake for days on end",
    20: "Very difficult to wear down, almost never feels fatigue",
    21: "Very difficult to wear down, almost never feels fatigue",
    22: "Never gets sick, even to the most virulent diseases",
    23: "Never gets sick, even to the most virulent diseases",
    24: "Tireless paragon of physical endurance",
    25: "Tireless paragon of physical endurance"
  },
  Intelligence: {
    1: "Animalistic, no longer capable of logic or reason",
    2: "Barely able to function, very limited speech and knowledge",
    3: "Barely able to function, very limited speech and knowledge",
    4: "Often resorts to charades to express thoughts",
    5: "Often resorts to charades to express thoughts",
    6: "Often misuses and mispronounces words",
    7: "Often misuses and mispronounces words",
    8: "Has trouble following trains of thought, forgets most unimportant things",
    9: "Has trouble following trains of thought, forgets most unimportant things",
    10: "Knows what they need to know to get by",
    11: "Knows what they need to know to get by",
    12: "Knows a bit more than is necessary, fairly logical",
    13: "Knows a bit more than is necessary, fairly logical",
    14: "Able to do math or solve logic puzzles mentally with reasonable accuracy",
    15: "Able to do math or solve logic puzzles mentally with reasonable accuracy",
    16: "Fairly intelligent, able to understand new tasks quickly",
    17: "Fairly intelligent, able to understand new tasks quickly",
    18: "Very intelligent, may invent new processes or uses for knowledge",
    19: "Very intelligent, may invent new processes or uses for knowledge",
    20: "Highly knowledgeable, probably the smartest person many people know",
    21: "Highly knowledgeable, probably the smartest person many people know",
    22: "Able to make Holmesian leaps of logic",
    23: "Able to make Holmesian leaps of logic",
    24: "Famous as a sage and genius",
    25: "Famous as a sage and genius"
  },
  Wisdom: {
    1: "Seemingly incapable of thought, barely aware",
    2: "Rarely notices important or prominent items, people, or occurrences",
    3: "Rarely notices important or prominent items, people, or occurrences",
    4: "Seemingly incapable of forethought",
    5: "Seemingly incapable of forethought",
    6: "Often fails to exert common sense",
    7: "Often fails to exert common sense",
    8: "Forgets or opts not to consider options before taking action",
    9: "Forgets or opts not to consider options before taking action",
    10: "Makes reasoned decisions most of the time",
    11: "Makes reasoned decisions most of the time",
    12: "Able to tell when a person is upset",
    13: "Able to tell when a person is upset",
    14: "Can get hunches about a situation that doesn't feel right",
    15: "Can get hunches about a situation that doesn't feel right",
    16: "Reads people and situations fairly well",
    17: "Reads people and situations fairly well",
    18: "Often used as a source of wisdom or decider of actions",
    19: "Often used as a source of wisdom or decider of actions",
    20: "Reads people and situations very well, almost unconsciously",
    21: "Reads people and situations very well, almost unconsciously",
    22: "Can tell minute differences among many situations",
    23: "Can tell minute differences among many situations",
    24: "Nearly prescient, able to reason far beyond logic",
    25: "Nearly prescient, able to reason far beyond logic"
  },
  Charisma: {
    1: "Barely conscious, incredibly tactless and non-empathetic",
    2: "Minimal independent thought, relies heavily on others to think instead",
    3: "Minimal independent thought, relies heavily on others to think instead",
    4: "Has trouble thinking of others as people",
    5: "Has trouble thinking of others as people",
    6: "Terribly reticent, uninteresting, or rude",
    7: "Terribly reticent, uninteresting, or rude",
    8: "Something of a bore or makes people mildly uncomfortable",
    9: "Something of a bore or makes people mildly uncomfortable",
    10: "Capable of polite conversation",
    11: "Capable of polite conversation",
    12: "Mildly interesting, knows what to say to the right people",
    13: "Mildly interesting, knows what to say to the right people",
    14: "Interesting, knows what to say to most people",
    15: "Interesting, knows what to say to most people",
    16: "Popular, receives greetings and conversations on the street",
    17: "Popular, receives greetings and conversations on the street",
    18: "Immediately likeable by many people, subject of favorable talk",
    19: "Immediately likeable by many people, subject of favorable talk",
    20: "Life of the party, able to keep people entertained for hours",
    21: "Life of the party, able to keep people entertained for hours",
    22: "Immediately likeable by almost everybody",
    23: "Immediately likeable by almost everybody",
    24: "Renowned for wit, personality, and/or looks",
    25: "Renowned for wit, personality, and/or looks"
  }
}; 